version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  redis:
    image: redis
    volumes:
      - redis_data:/data
volumes:
  redis_data:

